FROM espressif/idf:v4.2 AS base
MAINTAINER Brad Arnett

FROM base as micropython
WORKDIR /
RUN git clone https://github.com/micropython/micropython.git -b v1.19.1 --recurse
WORKDIR /micropython/mpy-cross
RUN make

FROM micropython as micropythonport
WORKDIR /micropython/ports/esp32
RUN make submodules

FROM micropythonport as firmwarebuild
COPY Docker/scripts /scripts

WORKDIR /

CMD ["/scripts/build_firmware.sh"]